package org.apache.jsp.pages.Erp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import geso.dms.center.util.Utility;
import geso.erp.beans.banhang.*;
import geso.erp.beans.banhang.imp.*;
import java.sql.ResultSet;
import java.util.Hashtable;
import java.util.List;

public final class BanhangNew_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.List<java.lang.String> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.List<java.lang.String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	IBanhang dmhBean = (IBanhang) session.getAttribute("dmhBean");
 	List<ISanpham> spList = dmhBean.getSpList();
	 String userId = (String) session.getAttribute("userId");
	String userTen = (String) session.getAttribute("userTen");
	 ResultSet khrs=dmhBean.getRsKh();
	Utility util = (Utility) session.getAttribute("util");
	
	String readonly="readonly";
	if(dmhBean.getIsCapNhat().equals("1") ){
		readonly="";
	}
	
	String disabled="disabled";
	if(dmhBean.getIsCapNhat().equals("1") ){
		disabled="";
	}
	NumberFormat formatter = new DecimalFormat("#,###,###.###");
	

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<TITLE>SalesUp - Project</TITLE>\r\n");
      out.write("<META http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<META http-equiv=\"Content-Style-Type\" content=\"text/css\">\r\n");
      out.write("<LINK rel=\"stylesheet\" type=\"text/css\" media=\"print\"\r\n");
      out.write("\thref=\"../css/impression.css\">\r\n");
      out.write("<LINK rel=\"stylesheet\" href=\"../css/main.css\" type=\"text/css\">\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"../css/mybutton.css\">\r\n");
      out.write("<LINK rel=\"stylesheet\" type=\"text/css\" href=\"../css/style.css\" />\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#mainContainer {\r\n");
      out.write("\twidth: 660px;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tborder-left: 3px double #000;\r\n");
      out.write("\tborder-right: 3px double #000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#formContent {\r\n");
      out.write("\tpadding: 5px;\r\n");
      out.write("}\r\n");
      out.write("/* END CSS ONLY NEEDED IN DEMO */\r\n");
      out.write("\r\n");
      out.write("/* Big box with list of options */\r\n");
      out.write("#ajax_listOfOptions {\r\n");
      out.write("\tposition: absolute; /* Never change this one */\r\n");
      out.write("\twidth: auto; /* Width of box */\r\n");
      out.write("\theight: 200px; /* Height of box */\r\n");
      out.write("\toverflow: auto; /* Scrolling features */\r\n");
      out.write("\tborder: 1px solid #317082; /* Dark green border */\r\n");
      out.write("\tbackground-color: #C5E8CD; /* White background color */\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tfont-size: 1.0em;\r\n");
      out.write("\tz-index: 100;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#ajax_listOfOptions div {re\r\n");
      out.write("\t/* General rule for both .optionDiv and .optionDivSelected */ margin:1px;\r\n");
      out.write("\tpadding: 1px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tfont-size: 1.0em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#ajax_listOfOptions .optionDiv { /* Div for each item in list */\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#ajax_listOfOptions .optionDivSelected { /* Selected item in the list */\r\n");
      out.write("\tbackground-color: #317082; /*mau khi di chuyen */\r\n");
      out.write("\tcolor: #FFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#ajax_listOfOptions_iframe {\r\n");
      out.write("\tbackground-color: #F00;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tz-index: 5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form {\r\n");
      out.write("\tdisplay: inline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#dhtmltooltip {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: -300px;\r\n");
      out.write("\twidth: 150px;\r\n");
      out.write("\tborder: 1px solid black;\r\n");
      out.write("\tpadding: 2px;\r\n");
      out.write("\tbackground-color: lightyellow;\r\n");
      out.write("\tvisibility: hidden;\r\n");
      out.write("\tz-index: 100;\r\n");
      out.write("\t/*Remove below line to remove shadow. Below line should always appear last within this CSS*/\r\n");
      out.write("\tfilter: progid:DXImageTransform.Microsoft.Shadow(color=gray, direction=135);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#dhtmlpointer {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: -300px;\r\n");
      out.write("\tz-index: 101;\r\n");
      out.write("\tvisibility: hidden;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/speechbubbles.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"../scripts/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../scripts/speechbubbles.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tjQuery(function($){ \r\n");
      out.write("\t\t $('.addspeech').speechbubble();});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<link href=\"../css/jquery-ui.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script src=\"../scripts/ui/jquery.ui.core.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../scripts/ui/jquery.ui.widget.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../scripts/ui/jquery.ui.datepicker.js\"\r\n");
      out.write("\ttype=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function() {\t\t\r\n");
      out.write("\t\t$( \".days\" ).datepicker({\t\t\t    \r\n");
      out.write("\t\t\t\tchangeMonth: true,\r\n");
      out.write("\t\t\t\tchangeYear: true\t\t\t\t\r\n");
      out.write("\t\t});            \r\n");
      out.write("\t});\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"../scripts/ajax.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../scripts/erp-spList.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"../scripts/dropdowncontent.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../scripts/cool_DHTML_tootip.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../scripts/jquery.autocomplete.js\"></script>\r\n");
      out.write("<link href=\"../css/select2.css\" rel=\"stylesheet\" />\r\n");
      out.write("<script src=\"../scripts/select2.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("     $(document).ready(function() { $(\"select\").select2();  });\r\n");
      out.write("     \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\tfunction replaces()\r\n");
      out.write("\t{\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar idsp = document.getElementsByName(\"idsp\");\r\n");
      out.write("\t\tvar masp = document.getElementsByName(\"masp\");\r\n");
      out.write("\t\tvar tensp = document.getElementsByName(\"tensp\");\r\n");
      out.write("\t\tvar donvitinh = document.getElementsByName(\"donvitinh\");\r\n");
      out.write("\t\tvar soluong = document.getElementsByName(\"soluong\");\r\n");
      out.write("\t\tvar dongia = document.getElementsByName(\"dongia\");\r\n");
      out.write("\t\tvar chietkhau = document.getElementsByName(\"chietkhau\");\r\n");
      out.write("\t\tvar thanhtien = document.getElementsByName(\"thanhtien\");\r\n");
      out.write("\t\t \r\n");
      out.write("\t\tvar sodong =  masp.length;\r\n");
      out.write("\t\tvar i;\r\n");
      out.write("\t\tfor(i = 0; i < sodong; i++)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(  masp.item(i).value != \"\"    )\r\n");
      out.write("\t\t\t{ \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar sp = masp.item(i).value;\r\n");
      out.write("\t\t\t\tvar pos = parseInt(sp.indexOf(\" -- \"));\r\n");
      out.write("\t\t\t\tvar slg = soluong.item(i).value.replace(/,/g,\"\"); \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(pos > 0)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tmasp.item(i).value = sp.substring(0, pos);\r\n");
      out.write("\t\t\t\t\tsp = sp.substr(parseInt(sp.indexOf(\" -- \")) + 3);\r\n");
      out.write("\t\t\t\t\ttensp.item(i).value = sp.substring(0, parseInt(sp.indexOf(\" [\")));\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tsp = sp.substr(parseInt(sp.indexOf(\" [\")) + 2);\r\n");
      out.write("\t\t\t\t\tdonvitinh.item(i).value = sp.substring(0, parseInt(sp.indexOf(\"] [\")));\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tsp = sp.substr(parseInt(sp.indexOf(\"] [\")) + 3);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tdongia.item(i).value = sp.substring(0, parseInt(sp.indexOf(\"] [\")));\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tsp = sp.substr(parseInt(sp.indexOf(\"] [\")) + 3);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tchietkhau.item(i).value = sp.substring(0, parseInt(sp.indexOf(\"] [\")));\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tsp = sp.substr(parseInt(sp.indexOf(\"] [\")) + 3);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tidsp.item(i).value = sp.substring(0, parseInt(sp.indexOf(\"]\")));\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tsoluong.item(i).focus();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(soluong.item(i).value != \"\")\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(dongia.item(i).value != \"\")\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tvar dgia = dongia.item(i).value.replace(/,/g,\"\"); \r\n");
      out.write("\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\tvar ck=chietkhau.item(i).value.replace(/,/g,\"\");\r\n");
      out.write("\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\tvar tt = parseFloat(slg) * ( parseFloat(dgia) - parseFloat(dgia) *parseFloat(ck) / 100 )  ;\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tthanhtien.item(i).value =  DinhDangDonGia( Math.round( tt * 1000 ) / 1000 );\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse \r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t \t\t\r\n");
      out.write("\t\t\t\t\t\tidsp.item(i).value = \"\";\r\n");
      out.write("\t\t\t\t\t\ttensp.item(i).value = \"\";\r\n");
      out.write("\t\t\t\t\t\tdonvitinh.item(i).value = \"\";\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\tsoluong.item(i).value = \"\";\r\n");
      out.write("\t\t\t\t\t\tdongia.item(i).value = \"\";\r\n");
      out.write("\t\t\t\t\t\tthanhtien.item(i).value = \"\";\r\n");
      out.write("\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t  \r\n");
      out.write("\t\tTinhTien();\r\n");
      out.write("\t\tsetTimeout(replaces, 500);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction TinhTien()\r\n");
      out.write("\t{\r\n");
      out.write("\t\t \r\n");
      out.write("\t\tvar soluong = document.getElementsByName(\"soluong\");\r\n");
      out.write("\t\tvar dongia = document.getElementsByName(\"dongia\");\r\n");
      out.write("\t\tvar chietkhau = document.getElementsByName(\"chietkhau\");\r\n");
      out.write("\t\tvar thanhtien = document.getElementsByName(\"thanhtien\");\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar tongtien = 0;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t\tfor(var i = 0; i < thanhtien.length; i++)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t//alert('TT: ' + thanhtien.item(i).value);\r\n");
      out.write("\t\t\t\t\tif( thanhtien.item(i).value != \"\" )\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tvar thanh_tien = thanhtien.item(i).value.replace(/,/g,\"\");\r\n");
      out.write("\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\ttongtien = parseFloat(tongtien) +  parseFloat(thanh_tien); \r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdocument.getElementById(\"tongtientruocvat\").value = DinhDangTien(Math.round(tongtien));\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction DinhDangTien(num) \r\n");
      out.write("\t {\r\n");
      out.write("\t    num = num.toString().replace(/$|\\,/g,'');\r\n");
      out.write("\t    if(isNaN(num))\r\n");
      out.write("\t    num = \"0\";\r\n");
      out.write("\t    sign = (num == (num = Math.abs(num)));\r\n");
      out.write("\t    num = Math.floor(num*100);\r\n");
      out.write("\t    num = Math.floor(num/100).toString();\r\n");
      out.write("\t    for (var i = 0; i < Math.floor((num.length-(1+i))/3); i++)\r\n");
      out.write("\t    num = num.substring(0,num.length-(4*i+3))+','+\r\n");
      out.write("\t    num.substring(num.length-(4*i+3));\r\n");
      out.write("\t    return (((sign)?'':'-') + num);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction FormatNumber(e)\r\n");
      out.write("\t{\r\n");
      out.write("\t\te.value = DinhDangDonGia(e.value);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction roundNumber(num, dec) \r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar result = Math.round(num*Math.pow(10,dec))/Math.pow(10,dec);\r\n");
      out.write("\t\treturn result;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction DinhDangDonGia(num) \r\n");
      out.write("\t{\r\n");
      out.write("\t\tnum = num.toString().replace(/$|\\,/g,'');\r\n");
      out.write("\t\t \r\n");
      out.write("\t\tvar sole = '';\r\n");
      out.write("\t\tif(num.indexOf(\".\") >= 0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tsole = num.substring(num.indexOf('.'));\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(isNaN(num))\r\n");
      out.write("\t\tnum = \"0\";\r\n");
      out.write("\t\tsign = (num == (num = Math.abs(num)));\r\n");
      out.write("\t\tnum = Math.floor(num*100);\r\n");
      out.write("\t\tnum = Math.floor(num/100).toString();\r\n");
      out.write("\t\tfor (var i = 0; i < Math.floor((num.length-(1+i))/3); i++)\r\n");
      out.write("\t\tnum = num.substring(0,num.length-(4*i+3)) + ',' + num.substring(num.length-(4*i+3));\r\n");
      out.write("\r\n");
      out.write("\t\tvar kq;\r\n");
      out.write("\t\tif(sole.length >= 0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tkq = (((sign)?'':'-') + num) + sole;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t\tkq = (((sign)?'':'-') + num);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//alert(kq);\r\n");
      out.write("\t\treturn kq;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction keypress(e) //Hàm dùng d? ngan ngu?i dùng nh?p các ký t? khác ký t? s? vào TextBox\r\n");
      out.write("\t{    \r\n");
      out.write("\t\tvar keypressed = null;\r\n");
      out.write("\t\tif (window.event)\r\n");
      out.write("\t\t\tkeypressed = window.event.keyCode; //IE\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t\tkeypressed = e.which; //NON-IE, Standard\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (keypressed < 48 || keypressed > 57)\r\n");
      out.write("\t\t{ \r\n");
      out.write("\t\t\tif (keypressed == 8 || keypressed == 127 || keypressed == 37 || keypressed == 39 || keypressed == 0 || keypressed == 46)\r\n");
      out.write("\t\t\t{//Phím Delete và Phím Back\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t function saveform()\r\n");
      out.write("\t {\t\r\n");
      out.write("\t \t document.forms['dmhForm'].action.value='save';\r\n");
      out.write("\t     document.forms['dmhForm'].submit();\r\n");
      out.write("\t }\r\n");
      out.write("\r\n");
      out.write("\t function checkSanPham()\r\n");
      out.write("\t {\r\n");
      out.write("\t\t var masp = document.getElementsByName(\"masp\");\r\n");
      out.write("\t\t for(var hh = 0; hh < masp.length; hh++)\r\n");
      out.write("\t\t {\r\n");
      out.write("\t\t\tif(masp.item(hh).value != \"\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t return false;\r\n");
      out.write("\t }\r\n");
      out.write("\t \r\n");
      out.write("\t function submitform()\r\n");
      out.write("\t { \t\t\r\n");
      out.write("\t\t document.forms['dmhForm'].action.value='submit';\r\n");
      out.write("\t     document.forms[\"dmhForm\"].submit();\r\n");
      out.write("\t }\r\n");
      out.write("\t \r\n");
      out.write("\t function themmoi()\r\n");
      out.write("\t { \t\t\r\n");
      out.write("\t\t document.forms['dmhForm'].action.value='themmoi';\r\n");
      out.write("\t\t document.forms['dmhForm'].IsCapNhat.value='1';\r\n");
      out.write("\t     document.forms[\"dmhForm\"].submit();\r\n");
      out.write("\t }\r\n");
      out.write("\t \r\n");
      out.write("\t function quaylaiInit()\r\n");
      out.write("\t { \t\t\r\n");
      out.write("\t\t document.forms['dmhForm'].action.value='quaylaiInit';\r\n");
      out.write("\t\t document.forms['dmhForm'].IsCapNhat.value='0';\r\n");
      out.write("\t     document.forms[\"dmhForm\"].submit();\r\n");
      out.write("\t }\r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\t  function timkiem()\r\n");
      out.write("\t { \t\t\r\n");
      out.write("\t\t document.forms['dmhForm'].action.value='timkiem';\r\n");
      out.write("\t\t document.forms['dmhForm'].IsCapNhat.value='0';\r\n");
      out.write("\t     document.forms[\"dmhForm\"].submit();\r\n");
      out.write("\t }\r\n");
      out.write("\t \r\n");
      out.write("\t function VeCuoi()\r\n");
      out.write("\t { \t\t\r\n");
      out.write("\t\t document.forms['dmhForm'].action.value='VeCuoi';\r\n");
      out.write("\t\t document.forms['dmhForm'].IsCapNhat.value='0';\r\n");
      out.write("\t     document.forms[\"dmhForm\"].submit();\r\n");
      out.write("\t }\r\n");
      out.write("\t function VeDau()\r\n");
      out.write("\t { \t\t\r\n");
      out.write("\t\t document.forms['dmhForm'].action.value='VeDau';\r\n");
      out.write("\t\t document.forms['dmhForm'].IsCapNhat.value='0';\r\n");
      out.write("\t     document.forms[\"dmhForm\"].submit();\r\n");
      out.write("\t }\r\n");
      out.write("\t function DichuyenLui()\r\n");
      out.write("\t { \t\t\r\n");
      out.write("\t\t document.forms['dmhForm'].action.value='DichuyenLui';\r\n");
      out.write("\t\t document.forms['dmhForm'].IsCapNhat.value='0';\r\n");
      out.write("\t     document.forms[\"dmhForm\"].submit();\r\n");
      out.write("\t }\r\n");
      out.write("\t \r\n");
      out.write("\t function DichuyenToi()\r\n");
      out.write("\t { \t\t\r\n");
      out.write("\t\t document.forms['dmhForm'].action.value='DichuyenToi';\r\n");
      out.write("\t\t document.forms['dmhForm'].IsCapNhat.value='0';\r\n");
      out.write("\t     document.forms[\"dmhForm\"].submit();\r\n");
      out.write("\t }\r\n");
      out.write("\t function savekhachhang()\r\n");
      out.write("\t { \t\t\r\n");
      out.write("\t\t document.forms['dmhForm'].action.value='savekhachhang';\r\n");
      out.write("\t\t document.forms['dmhForm'].IsCapNhat.value='0';\r\n");
      out.write("\t     document.forms[\"dmhForm\"].submit();\r\n");
      out.write("\t }\r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\t function Chinhsua()\r\n");
      out.write("\t { \t\t\r\n");
      out.write("\t\t document.forms['dmhForm'].action.value='chinhsua';\r\n");
      out.write("\t\t document.forms['dmhForm'].IsCapNhat.value='0';\r\n");
      out.write("\t\t var  id_dh= document.forms['dmhForm'].id_dh.value;\r\n");
      out.write("\t\t if(id_dh==\"\"){\r\n");
      out.write("\t\t\t alert('Không xác định số chứng từ sửa,vui lòng kiểm tra lại');\r\n");
      out.write("\t\t\t return;\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t \r\n");
      out.write("\t     document.forms[\"dmhForm\"].submit();\r\n");
      out.write("\t }\r\n");
      out.write("\t \r\n");
      out.write("\r\n");
      out.write("\t function Xoa_banghi()\r\n");
      out.write("\t { \t\t\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t document.forms['dmhForm'].action.value='Xoa_banghi';\r\n");
      out.write("\t\t document.forms['dmhForm'].IsCapNhat.value='0';\r\n");
      out.write("\t\t var  id_dh= document.forms['dmhForm'].id_dh.value;\r\n");
      out.write("\t\t if(id_dh==\"\"){\r\n");
      out.write("\t\t\t alert('Không xác định số chứng từ xóa,vui lòng kiểm tra lại');\r\n");
      out.write("\t\t\t return;\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t if(!confirm('Bạn có chắc chắn muốn xóa chứng từ : '+id_dh+' này không?'))\r\n");
      out.write("\t\t {\r\n");
      out.write("\t\t \treturn false;\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t \r\n");
      out.write("\t     document.forms[\"dmhForm\"].submit();\r\n");
      out.write("\t }\r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\t function changeNoiDung()\r\n");
      out.write("\t {\r\n");
      out.write("\t\t document.forms['dmhForm'].action.value='changeSP';\r\n");
      out.write("\t     document.forms[\"dmhForm\"].submit();\r\n");
      out.write("\t }\r\n");
      out.write(" \r\n");
      out.write("\t function goBack()\r\n");
      out.write("\t {\r\n");
      out.write("\t  \twindow.history.back();\r\n");
      out.write("\t }\r\n");
      out.write("\t \r\n");
      out.write("\t function changeNoiDia()\r\n");
      out.write("\t {\r\n");
      out.write("\t\tdocument.forms['dmhForm'].nccId.value= \"\";\r\n");
      out.write("\t\tdocument.forms['dmhForm'].action.value='checkedNoiDia';\r\n");
      out.write("\t\tdocument.forms[\"dmhForm\"].submit();\r\n");
      out.write("\t\t\r\n");
      out.write("\t } \r\n");
      out.write("\tfunction addRow(pos)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar table = $('#nn_'+pos);\r\n");
      out.write("\t\ttable.append(\r\n");
      out.write("\t    \t'<tr>'+\r\n");
      out.write("\t       \t\t'<td> <input type=\"text\" name=\"sub_ngaynhan_'+pos+'\" class=\"days\"> </td>'+\r\n");
      out.write("\t\t\t\t'<td> <input type=\"text\" name=\"sub_soluong_'+pos+'\"> </td>'+\r\n");
      out.write("\t    \t'</tr>'\r\n");
      out.write("\t   \t\t\t);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction ThemNgay(pos)\r\n");
      out.write("\t{\r\n");
      out.write("\t\t var sl = window.prompt(\"Nhấp số lượng ngày muốn thêm\", '');\r\n");
      out.write("\t\t if(isNaN(sl) == false && sl < 30)\r\n");
      out.write("\t\t {\r\n");
      out.write("\t\t\t for(var i=0; i < sl ; i++)\r\n");
      out.write("\t\t\t\t addRow(pos);\r\n");
      out.write("\t\t\t $( \".days\" ).datepicker({\t\t\t    \r\n");
      out.write("\t\t\t\t\tchangeMonth: true,\r\n");
      out.write("\t\t\t\t\tchangeYear: true\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t else\r\n");
      out.write("\t\t {\r\n");
      out.write("\t\t\t alert('Số lượng bạn nhập không hợp lệ. Mọi lần bạn chỉ được thêm tối đa ngày');\r\n");
      out.write("\t\t\t return;\r\n");
      out.write("\t\t }\r\n");
      out.write("\t }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<BODY leftmargin=\"0\" bottommargin=\"0\" topmargin=\"0\" rightmargin=\"0\">\r\n");
      out.write("\t<form name=\"dmhForm\" method=\"post\" action=\"../../BanhangUpdateSvl\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"userId\" value='");
      out.print(userId);
      out.write("'> <input\r\n");
      out.write("\t\t\ttype=\"hidden\" name=\"action\" value=\"1\" /> <input type=\"hidden\"\r\n");
      out.write("\t\t\tname=\"id_dh\" value='");
      out.print(dmhBean.getSochungtu());
      out.write("'> <input\r\n");
      out.write("\t\t\ttype=\"hidden\" id=\"IsCapNhat\" name=\"IsCapNhat\"\r\n");
      out.write("\t\t\tvalue='");
      out.print(dmhBean.getIsCapNhat());
      out.write("'>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"main\" style=\"width: 100%; padding-left: 2px\">\r\n");
      out.write("\t\t\t<div align=\"left\" id=\"header\" style=\"width: 100%; float: none\">\r\n");
      out.write("\t\t\t\t<div style=\"width: 60%; padding: 5px; float: left\"\r\n");
      out.write("\t\t\t\t\tclass=\"tbnavigation\">Quản lý đơn hàng</div>\r\n");
      out.write("\t\t\t\t<div align=\"right\" style=\"padding: 5px\" class=\"tbnavigation\">\r\n");
      out.write("\t\t\t\t\tChào mừng bạn\r\n");
      out.write("\t\t\t\t\t");
      out.print( userTen );
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div align=\"left\" id=\"button\"\r\n");
      out.write("\t\t\t\tstyle=\"border: 1; width: 100%; height: 32px; padding: 1px; float: none\"\r\n");
      out.write("\t\t\t\tclass=\"tbdarkrow\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<TABLE border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t<TR class=\"tbdarkrow\">\r\n");
      out.write("\t\t\t\t\t\t");
if(!dmhBean.getIsCapNhat().equals("1")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<TD width=\"40px\" align=\"left\"><span id=\"btnthem\"> <A\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"javascript:themmoi()\"> <IMG src=\"../images/add32.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"Thêm mới\" alt=\"Luu lai\" border=\"1px\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border-style: outset\"></A>\r\n");
      out.write("\t\t\t\t\t\t</span></TD>\r\n");
      out.write("\t\t\t\t\t\t");
if(dmhBean.getTrangthai().equals("0") && dmhBean.getSochungtu().length()>0 && dmhBean.getIsCapNhat().equals("0")){ 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<TD width=\"50px\" align=\"left\"><A href=\"javascript:Chinhsua()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<IMG src=\"../images/edit32.png\" title=\"Chỉnh sửa\" alt=\"Luu lai\"\r\n");
      out.write("\t\t\t\t\t\t\t\tborder=\"1px\" style=\"border-style: outset\">\r\n");
      out.write("\t\t\t\t\t\t</A></TD>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<TD width=\"50px\" align=\"left\"><A\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:Xoa_banghi()\"> <IMG\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"../images/DeleteRed_32.png\" title=\"Xóa\" alt=\"Luu lai\"\r\n");
      out.write("\t\t\t\t\t\t\t\tborder=\"1px\" style=\"border-style: outset\"></A></TD>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
if(dmhBean.getSochungtu().length()>0){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<TD width=\"50px\" align=\"left\"><A\r\n");
      out.write("\t\t\t\t\t\t\thref=\"../../DonHangInPdfSvl?userId=");
      out.print(userId );
      out.write("&print=");
      out.print( dmhBean.getSochungtu());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<IMG src=\"../images/printericon.png\" title=\"In Chúng từ\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"In Chúng từ\" border=\"1px\" style=\"border-style: outset\">\r\n");
      out.write("\t\t\t\t\t\t</A></TD>\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
if(dmhBean.getSochungtu().length()>0){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<TD width=\"50px\" align=\"left\"><A\r\n");
      out.write("\t\t\t\t\t\t\thref=\"../../DonHangInExcelSvl?userId=");
      out.print(userId );
      out.write("&excel=");
      out.print( dmhBean.getSochungtu());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<IMG src=\"../images/excel.gif\" title=\"In Chúng từ\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"In Chúng từ\" border=\"1px\" style=\"border-style: outset\">\r\n");
      out.write("\t\t\t\t\t\t</A></TD>\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
if(  dmhBean.getIsCapNhat().equals("1")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<TD width=\"30px\" align=\"left\"><A href=\"javascript:saveform()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<IMG src=\"../images/1455966997_save.png\" title=\"Save\" alt=\"Save\"\r\n");
      out.write("\t\t\t\t\t\t\t\tborder=\"1px\" style=\"border-style: outset\">\r\n");
      out.write("\t\t\t\t\t\t</A></TD>\r\n");
      out.write("\t\t\t\t\t\t<TD width=\"30px\" align=\"left\"><span id=\"btnUndo\"> <A\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"javascript:quaylaiInit()\"> <IMG\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"../images/Back_undo.png\" title=\"Undo\" alt=\"Undo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tborder=\"1px\" style=\"border-style: outset\"></A>\r\n");
      out.write("\t\t\t\t\t\t</span></TD>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<TD width=\"50px\" align=\"left\"></TD>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"30px\" align=\"left\"><A href=\"javascript:VeCuoi()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<IMG src=\"../images/back_first.png\" title=\"Về cuối\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"Về cuối\" border=\"1px\" style=\"border-style: outset\">\r\n");
      out.write("\t\t\t\t\t\t</A></td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"30px\" align=\"left\"><A\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:DichuyenLui()\"> <IMG\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"../images/back_1.png\" title=\"Lùi\" alt=\"Lùi\" border=\"1px\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"border-style: outset\"></A></td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"30px\" align=\"left\"><input\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 100px; height: 30px; border-style: outset\"\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"text\" name=\"chungtutimkiem\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"");
      out.print(dmhBean.getchungtutimkiem());
      out.write("\" onchange=\"timkiem()\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"30px\" align=\"left\"><A\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:DichuyenToi()\"> <IMG\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"../images/next_1.png\" title=\"Lùi\" alt=\"Tới\" border=\"1px\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"border-style: outset\"></A></td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"30px\" align=\"left\"><A href=\"javascript:VeDau()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<IMG src=\"../images/next_e.png\" title=\"Lùi\" alt=\"Về Đầu\"\r\n");
      out.write("\t\t\t\t\t\t\t\tborder=\"1px\" style=\"border-style: outset\">\r\n");
      out.write("\t\t\t\t\t\t</A></td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"30px\" align=\"left\"><A href=\"javascript:timkiem()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<IMG src=\"../images/timkiem_e.png\" title=\"Tìm kiếm\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"Tìm kiếm\" border=\"1px\" style=\"border-style: outset\">\r\n");
      out.write("\t\t\t\t\t\t</A></td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t");
 
										String trangthai_="";
										if(dmhBean.getTrangthai().equals("0")){
											trangthai_="CHƯA CHỐT";
										}else if(dmhBean.getTrangthai().equals("1")){
											trangthai_="ĐÃ CHỐT";
										}else if(dmhBean.getTrangthai().equals("2")){
											trangthai_="ĐÃ XÓA";
										}
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"font-size: 14px; font-weight: bold; color: red;\">\r\n");
      out.write("\t\t\t\t\t\t\t\tSỐ CHỨNG TỪ:\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(dmhBean.getSochungtu());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t. Trạng thái:\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(trangthai_ );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t</TABLE>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div align=\"left\" style=\"width: 100%; float: none; clear: left\">\r\n");
      out.write("\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t<legend class=\"legendtitle\"> Thông báo</legend>\r\n");
      out.write("\t\t\t\t\t<textarea name=\"dataerror\" id=\"Msg\" rows=\"1\" readonly=\"readonly\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 100%\">");
      out.print(dmhBean.getMsg());
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div align=\"left\" style=\"width: 100%; float: none; clear: left\">\r\n");
      out.write("\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t<legend class=\"legendtitle\"> Đơn bán hàng</legend>\r\n");
      out.write("\t\t\t\t\t<div style=\"float: none; width: 100%\" align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t<TABLE width=\"100%\" cellpadding=\"4\" cellspacing=\"0\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD class=\"plainlabel\">Khách hàng</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD class=\"plainlabel\"><select ");
      out.print(disabled);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"khachangid\" style=\"width: 500px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option></option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
if(khrs!=null) {
										while(khrs.next()) {
											if(khrs.getString("pk_seq").equals(dmhBean.getKhId())){
												
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print(khrs.getString("pk_seq"));
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tselected=\"selected\">");
      out.print(khrs.getString("ten") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											}else{
												 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print(khrs.getString("pk_seq"));
      out.write('"');
      out.write('>');
      out.print(khrs.getString("ten") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											}
										}
									 	
										 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
 }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</select> <a href=\"\" id=\"noidungGhiChu\" rel=\"ndGhiChu\"> &nbsp; <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"Thêm khách hàng\" src=\"../images/vitriluu.png\">Thêm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tkhách hàng\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<DIV id=\"ndGhiChu\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"position: absolute; visibility: hidden; border: 9px solid #80CB9B; background-color: white; width: 500px; min-height: 150px; overflow: auto; padding: 4px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<table width=\"100%\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th colspan=\"2\" width=\"500px\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"font-size: 14px; font-weight: bold;\">THÊM KHÁCH\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tHÀNG</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"20%\">Mã</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"80%\"><input style=\"width: 100%\" name=\"makh\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" value=\"");
      out.print(dmhBean.getKhMa() );
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"300px\">Tên</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"300px\"><input style=\"width: 100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"tenkh\" type=\"text\" value=\"");
      out.print(dmhBean.getKhten() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"300px\">Địa chỉ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"300px\"><input style=\"width: 100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" name=\"diachikh\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(dmhBean.getKhDiachi() );
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"300px\">Điện thoại</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"300px\"><input style=\"width: 100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" name=\"dienthoaikh\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(dmhBean.getKhDienThoai() );
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"300px\"><A href=\"javascript:savekhachhang()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<IMG src=\"../images/1455966997_save.png\" title=\"Save\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\talt=\"Save\" border=\"1px\" style=\"border-style: outset\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tLưu khách hàng\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</A> <a href=\"javascript:dropdowncontent.hidediv('ndGhiChu')\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<IMG src=\"../images/exit_1.png\" title=\"Close\" alt=\"Close\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tborder=\"1px\" style=\"border-style: outset\"> Đóng tab\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</DIV></TD>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD class=\"plainlabel\" valign=\"top\" width=\"150px\">Ngày\r\n");
      out.write("\t\t\t\t\t\t\t\t\tchứng từ</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD class=\"plainlabel\" valign=\"top\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"days\" id=\"ngaymuahang\" name=\"ngaymuahang\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print( dmhBean.getNgaymuahang() );
      out.write("\" maxlength=\"10\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(readonly);
      out.write(" /></TD>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD class=\"plainlabel\">Ghi chú</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD class=\"plainlabel\" colspan=\"3\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"ghichu\" style=\"width: 500px\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(dmhBean.getGhiChu());
      out.write('"');
      out.write(' ');
      out.print(readonly);
      out.write("></TD>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<TR>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD class=\"plainlabel\">Thành tiền</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD class=\"plainlabel\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"tongtientruocvat\" id=\"tongtientruocvat\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(dmhBean.getTongtienchuaVat());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"text-align: right; font-size: 14px; font-weight: bold;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\treadonly=\"readonly\"></TD>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD class=\"plainlabel\">Thanh toán</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD class=\"plainlabel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 if(dmhBean.getIsThanhToanHet().equals("1") ) { 
      out.write(" <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"text\" name=\"tienthanhtoan\" id=\"tienthanhtoan\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print( formatter.format(dmhBean.getTienThanhToan()));
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"text-align: right; font-size: 14px; font-weight: bold;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\treadonly=\"readonly\"> ");
}else{ 
      out.write(" <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"tienthanhtoan\" id=\"tienthanhtoan\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print( formatter.format(dmhBean.getTienThanhToan()));
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"text-align: right; font-size: 14px; font-weight: bold;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
} 
      out.write(' ');
 if(dmhBean.getIsThanhToanHet().equals("1") ) { 
      out.write(" <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"checkbox\" name=\"isthanhtoanhet\" value=\"1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tchecked=\"checked\"> Thanh toán hết ");
}else{ 
      out.write(" <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"checkbox\" name=\"isthanhtoanhet\" value=\"1\"> Thanh\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttoán hết ");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</TABLE>\r\n");
      out.write("\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div align=\"left\" style=\"width: 100%; float: none; clear: none;\">\r\n");
      out.write("\t\t\t\t\t\t<TABLE class=\"tabledetail\" width=\"100%\" border=\"0\" cellpadding=\"2\"\r\n");
      out.write("\t\t\t\t\t\t\tcellspacing=\"2\" style=\"font-size: 14px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<TR class=\"tbheader\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<TH align=\"center\" width=\"30px\">STT</TH>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<TH align=\"center\" width=\"10%\">Mã hàng mua</TH>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TH align=\"center\" width=\"15%\">Tên hàng mua</TH>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<TH align=\"center\" width=\"5%\">ĐVT</TH>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TH align=\"center\" width=\"5%\">Số lượng</TH>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TH align=\"center\" width=\"10%\">Đơn giá</TH>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TH align=\"center\" width=\"10%\">Chiết khấu</TH>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TH align=\"center\" width=\"10%\">Thành tiền</TH>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</TR>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
 int count = 0; 
								if(spList.size() > 0) { 
									for(int i = 0; i < spList.size(); i++) { 
										ISanpham sp = spList.get(i);
										
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD align=\"center\" width=\"2%\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print( i + 1 );
      out.write("\" style=\"text-align: center;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\treadonly=\"readonly\"> <input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print( sp.getPK_SEQ() );
      out.write("\" name=\"idsp\" style=\"width: 100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\treadonly=\"readonly\"></TD>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD align=\"center\" width=\"8%\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"masp\" style=\"width: 100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print( sp.getMasanpham() );
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeyup=\"ajax_showOptions(this,'donmuahang',event)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tAUTOCOMPLETE=\"off\" ");
      out.print(readonly);
      out.write("></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD align=\"left\" width=\"10%\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print( sp.getTensanpham() );
      out.write("\" name=\"tensp\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 100%\" readonly=\"readonly\"></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD align=\"center\" width=\"6%\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print( sp.getDonvitinh() );
      out.write("\" name=\"donvitinh\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 100%\"></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD align=\"center\" width=\"7%\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print( formatter.format(sp.getSoluong()) );
      out.write("\" name=\"soluong\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 100%; text-align: right;\" ");
      out.print(readonly);
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD align=\"center\" width=\"8%\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(formatter.format(sp.getDongia()) );
      out.write("\" name=\"dongia\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 100%; text-align: right;\" ");
      out.print(readonly);
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD align=\"center\" width=\"8%\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print( sp.getChietkhau() );
      out.write("\" name=\"chietkhau\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 100%; text-align: right;\" ");
      out.print(readonly);
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD align=\"center\" width=\"8%\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print( formatter.format(sp.getThanhtien()) );
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"thanhtien\" style=\"width: 100%; text-align: right;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\treadonly=\"readonly\"></TD>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
 count++; }
								} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
 for(int i = count; i < 20; i++) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD align=\"center\" width=\"2%\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print( i + 1 );
      out.write("\" style=\"text-align: center;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\treadonly=\"readonly\"> <input type=\"hidden\" value=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"idsp\" style=\"width: 100%\" readonly=\"readonly\"></TD>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD align=\"center\" width=\"8%\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"masp\" style=\"width: 100%\" value=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeyup=\"ajax_showOptions(this,'donmuahang',event)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tAUTOCOMPLETE=\"off\" ");
      out.print(readonly);
      out.write("></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD align=\"left\" width=\"10%\"><input type=\"text\" value=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"tensp\" style=\"width: 100%\" readonly=\"readonly\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD align=\"center\" width=\"6%\"><input type=\"text\" value=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"donvitinh\" style=\"width: 100%\"></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD align=\"center\" width=\"7%\"><input type=\"text\" value=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"soluong\" style=\"width: 100%; text-align: right;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeyup=\"FormatNumber(this)\" ");
      out.print(readonly);
      out.write("></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD align=\"center\" width=\"8%\"><input type=\"text\" value=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"dongia\" style=\"width: 100%; text-align: right;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeyup=\"FormatNumber(this)\" ");
      out.print(readonly);
      out.write("></TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD align=\"center\" width=\"8%\"><input type=\"text\" value=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"chietkhau\" style=\"width: 100%; text-align: right;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonkeyup=\"FormatNumber(this)\" ");
      out.print(readonly);
      out.write("></TD>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<TD align=\"center\" width=\"8%\"><input type=\"text\" value=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"thanhtien\" style=\"width: 100%; text-align: right;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\treadonly=\"readonly\"></TD>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"tbfooter\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"12\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</TABLE>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\treplaces();\r\n");
      out.write("\tdropdowncontent.init(\"noidungGhiChu\", \"right-botom\", 500, \"click\");\r\n");
      out.write(" \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\t\t");

		if(spList!=null){
			spList.clear();
		}
 		 
 		session.setAttribute("dmhBean",null);
		dmhBean.close();
	
      out.write("\r\n");
      out.write("\t</form>\r\n");
      out.write("</BODY>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
