package org.apache.jsp.pages.Erp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import java.util.ArrayList;
import java.sql.ResultSet;
import geso.training.bean.donhang.IDonHang;
import geso.training.bean.donhang.imp.DonHang;
import geso.training.bean.sanpham.ISanPham;
import geso.training.bean.sanpham.imp.SanPham;
import java.util.Iterator;

public final class donhangupdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.List<java.lang.String> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.List<java.lang.String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	//IDonHang obj =(IDonHang)session.getAttribute("donhangupdate");
	ISanPham sp =(ISanPham)session.getAttribute("donhangupdate");
    String userId=(String)session.getAttribute("userId");
	String userTen=(String)session.getAttribute("userTen");
	//String userId=obj.getUserId();
	//String action=(String)session.getAttribute("action");
	List<ISanPham> listSp =sp.getListSp();
	//List<IDonHang> ds_sanpham = obj.getDs_sanpham();
	//ResultSet khRs=obj.getKhRs();

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Best-Project</title>\r\n");
      out.write("<META http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<META http-equiv=\"Content-Style-Type\" content=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("<LINK rel=\"stylesheet\"type=\"text/css\" media=\"print\" href=\"../css/impression.css\">\r\n");
      out.write("<LINK rel=\"stylesheet\"type=\"text/css\" href=\"../css/main.css\">\r\n");
      out.write("<link rel=\"stylesheet\"type=\"text/css\" href=\"../css/mybutton.css\">\r\n");
      out.write("<link rel=\"stylesheet\"type=\"text/css\" href=\"../css/style.css\"/>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#mainContainer {\r\n");
      out.write("\twidth: 660px;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tborder-left: 3px double #000;\r\n");
      out.write("\tborder-right: 3px double #000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#formContent {\r\n");
      out.write("\tpadding: 5px;\r\n");
      out.write("}\r\n");
      out.write("/* END CSS ONLY NEEDED IN DEMO */\r\n");
      out.write("\r\n");
      out.write("/* Big box with list of options */\r\n");
      out.write("#ajax_listOfOptions {\r\n");
      out.write("\tposition: absolute; /* never change this one */\r\n");
      out.write("\twidth: auto; /* Width of box */\r\n");
      out.write("\theight: 200px; /* Height of box */\r\n");
      out.write("\toverflow: auto; /*Scrolling features */\r\n");
      out.write("\tborder: 1px solid #317082; /* Dark green border */\r\n");
      out.write("\tbackground-color: #C5E8CD; /* White background color */\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tfont-size: 1.0em;\r\n");
      out.write("\tz-index: 100;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#ajax_listOfOptions div {\r\n");
      out.write("\t/* General rule for both .optionDiv and .optionDivSelected */\r\n");
      out.write("\tmargin: 1px;\r\n");
      out.write("\tpadding: 1px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tfont-size: 1.0em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#ajax_listOfOptions .optionDiv { /* Div for each item in list */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#ajax_listOfOptions .optionDivSelected { \r\n");
      out.write("\t/* Selected item in the list */\r\n");
      out.write("\tbackground-color: #317082; /*color as move */\r\n");
      out.write("\tcolor: #FFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#ajax_listOfOptions_iframe {\r\n");
      out.write("\tbackground-color: #F00;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tz-index: 5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form {\r\n");
      out.write("\tdisplay: inline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#dhtmltooltip {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: -300px;\r\n");
      out.write("\twidth: 150px;\r\n");
      out.write("\tborder: 1px solid black;\r\n");
      out.write("\tpadding: 2px;\r\n");
      out.write("\tbackground-color: lightyellow;\r\n");
      out.write("\tvisibility: hidden;\r\n");
      out.write("\tz-index: 100;\r\n");
      out.write("\t/*Remove below line to remove shadow. Below line should always appear last\r\n");
      out.write("within this css */\r\n");
      out.write("\tfilter: progrid:DXImageTransform.Microsoft.Shadow(color=gray, direction=135);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#dhtmlpointer {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: -300px;\r\n");
      out.write("\tz-index: 101;\r\n");
      out.write("\tvisibility: hidden;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/speechbubbles.css\" />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"../scripts/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../scripts/speechbubbles.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tjQuery(function($){\r\n");
      out.write("\t\t$(\".addspeech\").speechbubble();\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"../scripts/jquery.min.1.7.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/jquery-ui.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"../scripts/ui/jquery.ui.core.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../scripts/ui/jquery.ui.widget.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../scripts/ui/jquery.ui.datepicker.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t$(\".days\").datepicker({\r\n");
      out.write("\t\t\tchangeMonth:true,\r\n");
      out.write("\t\t\tchangeYear:true\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"../scripts/ajax.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../scripts/ajax-dynamic-list.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../scripts/dropdowncontent.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../scripts/cool_DHTML_tootip.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../scripts/jquery.autocomplete.js\"></script>\r\n");
      out.write("<!--<link href=\"../css/select2.css\" rel=\"stylesheet\" />\r\n");
      out.write("<script src=\"../scripts/select2.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("     $(document).ready(function() { $(\"select\").select2();\r\n");
      out.write("     });\r\n");
      out.write("     \r\n");
      out.write("</script>-->\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("function TinhTien(){\r\n");
      out.write("\tvar thanhtien=document.getElementsByName(\"thanhtien1\");\r\n");
      out.write("\tvar tongtien = 0;\r\n");
      out.write("\tfor(var i=0;i<thanhtien.length;i++){\r\n");
      out.write("\t\tvar thanh_tien=thanhtien.item(i).value;\r\n");
      out.write("\t\twhile(thanh_tien.match(\",\"))\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tthanh_tien=thanh_tien.replace(\",\",\"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(thanh_tien != \"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\ttongtien=parseFloat(tongtien) + parseFloat(thanh_tien);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tvar tienchuaVAT = tongtien;\r\n");
      out.write("\tdocument.getElementById(\"sotienchuaVAT\").value = DinhDangTien(tienchuaVAT);\r\n");
      out.write("\t\r\n");
      out.write("\tvar vat=document.getElementById(\"VAT\").value;\r\n");
      out.write("\tif(vat==\"\"){\r\n");
      out.write("\t\tvat= \"0\";\r\n");
      out.write("\t}\r\n");
      out.write("\tvar tongtiencoVAT = tienchuaVAT+(parseFloat(vat))/100*tienchuaVAT;\r\n");
      out.write("\tdocument.getElementById(\"sotiencoVAT\").value=DinhDangTien(Math.round(tongtiencoVAT));\r\n");
      out.write("}\r\n");
      out.write("function roundNumber(num,dec){\r\n");
      out.write("\tvar result=Math.round(num*Math.pow(10, dec))/Math.pow(10,dec);\r\n");
      out.write("\treturn result;\r\n");
      out.write("}\r\n");
      out.write("function DinhDangTien(num){\r\n");
      out.write("\tnum=num.toString().replace(/$|\\,/g,'');\r\n");
      out.write("\tif(isNaN(num)){\r\n");
      out.write("\t\tnum= \"0\";\r\n");
      out.write("\t\tsign=(num==(num=Math.abs(num)));\r\n");
      out.write("\t\tnum=Math.floor(num*100+0.50000000001);\r\n");
      out.write("\t\tnum=Math.floor(num/100).toString();\r\n");
      out.write("\t}\r\n");
      out.write("\tfor(var i=0;i<Math.floor((num.length-(1+i))/3);i++){\r\n");
      out.write("\t\tnum=num.substring(0, num.length-(4*i+3))+\",\"+\r\n");
      out.write("\t\tnum.substring(num.length-(4*i+3));\r\n");
      out.write("\t}\r\n");
      out.write("\treturn (((sign)?'':'-')+num);\r\n");
      out.write("}\r\n");
      out.write("function replaces(){\r\n");
      out.write("\tvar khTen=document.getElementsByName(\"khTen\");\r\n");
      out.write("\tvar smartId=document.getElementsByName(\"smartId\");\r\n");
      out.write("\tfor(var i=0;i<smartId.length;i++){\r\n");
      out.write("\t\tvar tem=smartId.item(0).value;\r\n");
      out.write("\t\tif(tem==\"\"){\r\n");
      out.write("\t\t\tkhTen.item(0).value = \"\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"khId\").value = \"\";\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(parseInt(tem.indexOf(\"-->\"))>0){\r\n");
      out.write("\t\t\tvar tmp=tem.substring(0,parseInt(tem.indexOf(\"-->[\")));\r\n");
      out.write("\t\t\tdocument.getElementById(\"khId\").value=tmp.substring(parseInt(tem.indexOf(\"-\"))+1,tmp.length);\r\n");
      out.write("\t\t\tsmartId.item(0).value=tmp.substring(0,parseInt(tem.indexOf(\"-\")));\r\n");
      out.write("\t\t\tkhTen.item(0).value=tem.substring(parseInt(tem.indexOf(\"-->[\"))+4, parseInt(tem.indexOf(\"]\")));\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tvar idsp=document.getElementsByName(\"spId\");\r\n");
      out.write("\tvar masp=document.getElementsByName(\"masp\");\r\n");
      out.write("\tvar tensp=document.getElementsByName(\"tensp1\");\r\n");
      out.write("\tvar donvitinh=document.getElementsByName(\"donvitinh1\");\r\n");
      out.write("\tvar dongia=document.getElementsByName(\"dongia1\");\r\n");
      out.write("\tvar soluong=document.getElementsByName(\"soluong\");\r\n");
      out.write("\tvar chietkhau=document.getElementsByName(\"chietkhau1\");\r\n");
      out.write("\tvar thanhtien=document.getElementsByName(\"thanhtien1\");\r\n");
      out.write("\t/*\r\n");
      out.write("\tfor(var i=0;i<masp.length;i++){\r\n");
      out.write("\t\tvar tem=masp.item(i).value;\r\n");
      out.write("\t\tif(tem==\"\"){\r\n");
      out.write("\t\t\ttensp.item(i).value=\"\";\r\n");
      out.write("\t\t\tdongia.item(i).value = \"\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"spId\").value = \"\";\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(parseInt(tem.indexOf(\"-->\"))>0){\r\n");
      out.write("\t\t\tvar tmp=tem.substring(0,parseInt(tem.indexOf(\"-->\")));\r\n");
      out.write("\t\t\tdocument.getElementById(\"spId\").value=tmp.substring(parseInt(tmp.indexOf(\"-\"))+1,tmp.length);\r\n");
      out.write("\t\t\tmasp.item(i).value=tmp.substring(0,parseInt(tem.indexOf(\"-\")));\r\n");
      out.write("\t\t\t//idsp.item(i).value=tmp.substring(parseInt(tem.indexOf(\"-\"))+1, tmp.length);\r\n");
      out.write("\t\t\tvar tkp=tem.substring(parseInt(tem.indexOf(\"-->\"))+3, tem.length);\r\n");
      out.write("\t\t\ttensp.item(i).value=tkp.substring(0,parseInt(tkp.indexOf(\"-\")));\r\n");
      out.write("\t\t\tdongia.item(i).value=tkp.substring(parseInt(tkp.indexOf(\"-\"))+1, tkp.length);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}*/\r\n");
      out.write("\tfor(var i=0;i<masp.length;i++){\r\n");
      out.write("\t\tif(masp.item(i).value!= \"\"){\r\n");
      out.write("\t\t\tvar sp=masp.item(i).value;\r\n");
      out.write("\t\t\tif((parseInt(sp.indexOf(\"-->\")))>0){\r\n");
      out.write("\t\t\t\tvar tmp=sp.substring(0,parseInt(sp.indexOf(\"-->\")));\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"spId\").value=tmp.substring(parseInt(tmp.indexOf(\"-\"))+1,tmp.length);\r\n");
      out.write("\t\t\t\tmasp.item(i).value=tmp.substring(0,parseInt(sp.indexOf(\"-\")));\r\n");
      out.write("\t\t\t\t//idsp.item(i).value=tmp.substring(parseInt(tem.indexOf(\"-\"))+1, tmp.length);\r\n");
      out.write("\t\t\t\tvar tkp=sp.substring(parseInt(sp.indexOf(\"-->\"))+3, sp.length);\r\n");
      out.write("\t\t\t\ttensp.item(i).value=tkp.substring(0,parseInt(tkp.indexOf(\"-\")));\r\n");
      out.write("\t\t\t\tdongia.item(i).value=tkp.substring(parseInt(tkp.indexOf(\"-\"))+1, tkp.length);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//break;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t/*\r\n");
      out.write("\t\t\tvar pos=parseInt(sp.indexOf(\" - \"));\r\n");
      out.write("\t\t\tif(pos>0){\r\n");
      out.write("\t\t\t\tmasp.item(i).value=sp.substring(0, pos);\r\n");
      out.write("\t\t\t\tsp=sp.substr(parseInt(sp.indexOf(\" - \"))+3);\r\n");
      out.write("\t\t\t\ttensp.item(i).value=sp.substring(0,parseInt(sp.indexOf(\" [\")));\r\n");
      out.write("\t\t\t\tsp=sp.substr(parseInt(sp.indexOf(\" [\"))+2);\r\n");
      out.write("\t\t\t\tdonvitinh.item(i).value=sp.substring(0,parseInt(sp.indexOf(\"] [\")));\r\n");
      out.write("\t\t\t\tsp=sp.substr(parseInt(sp.indexOf(\"] [\"))+3);\r\n");
      out.write("\t\t\t\tdongia.item(i).value=sp.substring(0,parseInt(sp.indexOf(\"] [\")));\r\n");
      out.write("\t\t\t\tsp=sp.substr(parseInt(sp.indexOf(\"] [\"))+3);\r\n");
      out.write("\t\t\t\tchietkhau.item(i).value=sp.substring(0,parseInt(sp.indexOf(\"] [\")));\r\n");
      out.write("\t\t\t\tsp=sp.substr(parseInt(sp.indexOf(\"] [\"))+3);\r\n");
      out.write("\t\t\t\tidsp.item(i).value=sp.substring(0, parseInt(sp.indexOf(\"]\")));\r\n");
      out.write("\t\t\t\tsoluong.item(i).focus();\r\n");
      out.write("\t\t\t}*/\r\n");
      out.write("\t\t\tvar so_luong=soluong.item(i).value;\r\n");
      out.write("\t\t\twhile(so_luong.match(\",\")){\r\n");
      out.write("\t\t\t\tso_luong=so_luong.replace(\",\",\"\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(parseInt(so_luong)>0){\r\n");
      out.write("\t\t\t\tvar don_gia=dongia.item(i).value;\r\n");
      out.write("\t\t\t\tif(don_gia >0){\r\n");
      out.write("\t\t\t\t\twhile(don_gia.match(\",\")){\r\n");
      out.write("\t\t\t\t\t\tdon_gia=don_gia.replace(\",\",\"\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tvar chiet_khau=chietkhau.item(i).value;\r\n");
      out.write("\t\t\t\t\twhile(chiet_khau.match(\",\")){\r\n");
      out.write("\t\t\t\t\t\tchiet_khau=chiet_chietkhau.replace(\",\",\"\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tvar tt=parseInt(so_luong)*(parseFloat(don_gia)-parseFloat(don_gia)*parseFloat(chiet_khau) / 100);\r\n");
      out.write("\t\t\t\t\tthanhtien.item(i).value=DinhDangTien(roundNumber(tt, 2));\r\n");
      out.write("\t\t\t\t\tTinhTien();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tthanhtien.item(i).value = \"\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tidsp.item(i).value=\"\";\r\n");
      out.write("\t\t\ttensp.item(i).value=\"\";\r\n");
      out.write("\t\t\tdonvitinh.item(i).value=\"\";\r\n");
      out.write("\t\t\tdongia.item(i).value=\"\";\r\n");
      out.write("\t\t\tsoluong.item(i).value=\"\";\r\n");
      out.write("\t\t\tchietkhau.item(i).value=\"\";\r\n");
      out.write("\t\t\tthanhtien.item(i).value=\"\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tsetTimeout(replaces, 100);\r\n");
      out.write("}\r\n");
      out.write("function updateform(){\r\n");
      out.write("\tdocument.forms[\"donhanglist\"].action.value=\"hien\";\r\n");
      out.write("\tdocument.forms[\"donhanglist\"].submit();\r\n");
      out.write("}\r\n");
      out.write("function saveform(){\r\n");
      out.write("\tdocument.forms[\"donhanglist\"].action.value=\"luusua\";\r\n");
      out.write("\tdocument.forms[\"donhanglist\"].submit();\r\n");
      out.write("}\r\n");
      out.write("function goBack()\r\n");
      out.write("{\r\n");
      out.write(" \twindow.history.back();\r\n");
      out.write("}\r\n");
      out.write("function checkSanpham(){\r\n");
      out.write("\tvar masp = document.getElementsByName(\"masp\");\r\n");
      out.write("\tfor(var hh=0;hh<masp.length;hh++){\r\n");
      out.write("\t\tif(masp.item(hh).value !=\"\"){\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\treturn false;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body leftmargin=\"0\" bottommargin=\"0\" topmargin=\"0\" rightmargin=\"0\">\r\n");
      out.write("<form name=\"donhanglist\" method=\"post\" action=\"../../DonhangUpdatesvl\">\r\n");
      out.write("<input type=\"hidden\" name=\"action\" value=\"1\">\r\n");
      out.write("<input type=\"hidden\" id=\"khId\" name=\"khId\" value=\"\">\r\n");
      out.write("<input type=\"hidden\" id=\"spId\" name=\"spId\" value=\"\">\r\n");
      out.write("<input type=\"hidden\" name=\"userId\" value=\"");
      out.print(userId);
      out.write("\">\r\n");
      out.write("<input type=\"hidden\"name=\"madonhang\" value=\"");
      out.print(sp.getMadh() );
      out.write("\">\r\n");
      out.write("\t<table width=\"100%\" height=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"4\" align=\"left\" valign=\"top\" bgcolor=\"#FFFFFF\">\r\n");
      out.write("\t\t\t\t<table width=\"100%\" cellspacing=\"0\" cellpadding=\"2\" border=\"0\">\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t<tr height=\"22\">\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table width=\"100%\"cellspacing=\"0\"cellpadding=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<table width=\"100%\"cellpadding=\"0\"cellspacing=\"0\"border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr height=\"22\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"tbnavigation\"align=\"left\">&nbsp;Xử lý đơn hàng > Đơn hàng bán > Tạo mới</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"tbnavigation\"align=\"right\">Chào mừng nhà phân phối</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    </table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t<table width=\"100%\"cellspacing=\"0\"cellpadding=\"1\"border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table width=\"100%\" cellspacing=\"0\"cellpadding=\"0\"border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr class=\"tbdarkrow\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"../../Donhanglistsvl?userId=");
      out.print(userId);
      out.write("\"><img src=\"../images/Back30.png\" alt=\"Quay về\" title=\"Quay về\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tlongdesc=\"Quay về\"border=\"1\"style=\"border-style: outset\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"javascript:saveform()\"><img src=\"../images/Save30.png\" alt=\"Save\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"Save\"longdesc=\"Save\"border=\"1\"style=\"border-style: outset\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"javascript:updateform()\"><img src=\"../images/Edit30.png\" alt=\"Update\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"Update\"border=\"0\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t<table width=\"100%\"cellspacing=\"0\"cellpadding=\"0\"border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"legendtitle\" colspan=\"4\"align=\"left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<LEGEND class=\"legendtitle\">Báo lỗi nhập liệu</LEGEND>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea name=\"dataerror\"id=\"Msg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width:99.5%; color:#F00; font-weight:bold\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\treadonly=\"readonly\" rows=\"2\">");
      out.print(sp.getMsg() );
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t<table width=\"100%\"cellspacing=\"0\"cellpadding=\"0\"border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<LEGEND class=\"legendtitle\">Đơn hàng bán</LEGEND>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table width=\"100%\"cellspacing=\"0\"cellpadding=\"3\"border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"170px\"class=\"plainlabel\">Ngày giao dịch</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"plainlabel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\"class=\"days\"size=\"11\"name=\"ngaydonhang\"id=\"ngaydonhang\"value=\"");
      out.print(sp.getNgaydh());
      out.write("\"maxlength=\"10\"readonly /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"plainlabel\"><a href=\"\" id=\"noidungGhiChu\" rel=\"ndGhiChu\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"Thêm khách hàng\" src=\"../images/vitriluu.png\">Thêm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tkhách hàng\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<DIV id=\"ndGhiChu\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"position: absolute; visibility: hidden; border: 9px solid #80CB9B; background-color: white; width: 500px; min-height: 150px; overflow: auto; padding: 4px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<table width=\"100%\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th colspan=\"2\" width=\"500px\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"font-size: 14px; font-weight: bold;\">THÊM KHÁCH\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tHÀNG</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"20%\">Mã</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"80%\"><input style=\"width: 100%\" name=\"makh\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" value=\"");
      out.print(sp.getMakh() );
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"300px\">Tên</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"300px\"><input style=\"width: 100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"tenkh\" type=\"text\" value=\"");
      out.print(sp.getTenkh() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"300px\">Địa chỉ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"300px\"><input style=\"width: 100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" name=\"diachikh\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(sp.getKhDiachi() );
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"300px\">Điện thoại</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"300px\"><input style=\"width: 100%\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" name=\"dienthoaikh\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(sp.getKhDienthoai() );
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"300px\"><A href=\"javascript:savekhachhang()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<IMG src=\"../images/1455966997_save.png\" title=\"Save\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\talt=\"Save\" border=\"1px\" style=\"border-style: outset\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tLưu khách hàng\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</A> <a href=\"javascript:dropdowncontent.hidediv('ndGhiChu')\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<IMG src=\"../images/exit_1.png\" title=\"Close\" alt=\"Close\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tborder=\"1px\" style=\"border-style: outset\"> Đóng tab\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</DIV></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"plainlabel\">Trạng thái</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"plainlabel\"><select name=\"trangthai\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonchange=\"submitform()\" style=\"width: 200px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print(sp.getTrangThai());
      out.write("\">Toàn bộ</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

							                    	String mangMaTrangThai[] = {"0", "1", "2"};
						                    		String mangTenTrangThai[] = {"Chưa chốt", "Đã chốt", "Đã hủy"};
						                    		for(int i = 0; i < mangMaTrangThai.length; i++){
													 if(sp.getTrangThai().equals(mangMaTrangThai[i])){
													 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option selected=\"selected\" value=\"");
      out.print(mangMaTrangThai[i]);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print( mangTenTrangThai[i] );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");

													 }else{
													 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print( mangMaTrangThai[i] );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print( mangTenTrangThai[i] );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
 
													 }
												 }
						                    	
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"plainlabel\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"plainlabel\">Mã khách hàng</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"plainlabel\" width=\"250px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\"name=\"smartId\"id=\"smartId\"style=\"width:200px\"value=\"");
      out.print(sp.getMakh());
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"plainlabel\"width=\"190px\">Tên khách hàng - Địa chỉ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"plainlabel\"colspan=\"5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\"name=\"khTen\"id=\"khTen\"style=\"width:100%\"value=\"");
      out.print(sp.getTenkh());
      out.write("\"readonly /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr class=\"tblightrow\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"plainlabel\">VAT(%)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"plainlabel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\"name=\"VAT\"id=\"VAT\"value=\"");
      out.print(sp.getVat());
      out.write("\"onkeypress=\"return keypress(event);\">%</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"plainlabel\">Tổng số tiền</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"plainlabel\"colspan=\"5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\"name=\"sotienchuaVAT\"id=\"sotienchuaVAT\"value=\"");
      out.print(sp.getTongtientruocVat());
      out.write("\"readonly>VND</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr class=\"tblightrow\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"plainlabel\">Tổng số tiền(sau VAT)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"plainlabel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\"name=\"sotiencoVAT\"id=\"sotiencoVAT\"value=\"");
      out.print(sp.getTongtiensauVat());
      out.write("\"readonly>VND</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td class=\"plainlabel\">Mã đơn hàng</TD>\r\n");
      out.write("\t\t\t\t\t\t\t\t   \t\t<td class=\"plainlabel\"colspan=\"5\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"madonhang\"value=\"");
      out.print(sp.getMadh());
      out.write("\" placeholder=\"Ex: 100000\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table width=\"100%\"cellpadding=\"5\"border=\"0\"style=\"font-size: 15px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tbody id=\"san_pham\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr class=\"tbheader\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<TH align=\"left\" width=\"2%\">STT</TH>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th align=\"center\"width=\"8%\"height=\"20\">Mã sản phẩm</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th align=\"center\"width=\"15%\">Tên sản phẩm</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th align=\"center\"width=\"6%\">Số lượng</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th align=\"center\"width=\"6%\">DVT</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th align=\"center\"width=\"8%\">Đơn giá</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th align=\"center\"width=\"6%\">Chiết khấu</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th align=\"center\"width=\"10%\">Thành tiền</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");

													int j=0;
													if(listSp.size()>0){
														Iterator<ISanPham> iteratorSanPham = listSp.iterator();
														while(iteratorSanPham.hasNext()){
															ISanPham elementSanPham = iteratorSanPham.next();
															j++;
														
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"center\" width=\"2%\"><input type=\"text\"\r\n");
      out.write("                                                        value=\"");
      out.print(j);
      out.write("\" style=\"width:100%;text-align: center;\"readonly=\"readonly\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\"value=\"");
      out.print(elementSanPham.getPK_SEQ() );
      out.write("\"name=\"spId\"id=\"spId\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width:100%\"readonly=\"readonly\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"left\" width=\"8%\">\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\"name=\"masp\"id=\"masp\"value=\"");
      out.print(elementSanPham.getMaSP() );
      out.write("\"onkeyup=\"ajax_showOptions(this,'donhangsua',event)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tautocomplete=\"on\"style=\"width:100%\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"left\"width=\"15%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\"name=\"tensp1\"id=\"tensp1\"value=\"");
      out.print(elementSanPham.getTenSP() );
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\treadonly=\"readonly\"style=\"width:100%\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"center\"width=\"6%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"number\"name=\"soluong\"value=\"");
      out.print(elementSanPham.getSoLuong() );
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width:100%;text-align:center;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"right\"width=\"6%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\"name=\"donvitinh1\"value=\"");
      out.print(elementSanPham.getDVT() );
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width:100%;text-align:center;color:black;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"right\"width=\"8%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\"name=\"dongia1\"id=\"dongia1\"value=\"");
      out.print(elementSanPham.getDonGia() );
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width:100%;text-align:center;color:black;\"readonly=\"readonly\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"right\" width=\"6%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\"name=\"chietkhau1\"value=\"");
      out.print(elementSanPham.getChietkhau() );
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width:100%;text-align:center;color:black;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"right\"width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\"name=\"thanhtien1\"value=\"");
      out.print(elementSanPham.getThanhTien() );
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width:100%;text-align:center;color:black;\"readonly=\"readonly\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
}}
													
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

													for(int i=j;i<listSp.size()+20;i++){
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"center\" width=\"2%\"><input type=\"text\"\r\n");
      out.write("                                                        value=\"");
      out.print(i+1);
      out.write("\" style=\"width:100%;text-align: center;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\treadonly=\"readonly\"><input type=\"hidden\" value=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"spId\"id=\"spId\" style=\"width: 100%\" readonly=\"readonly\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"left\"width=\"8%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\"name=\"masp\"id=\"masp\"value=\"\"onkeyup=\"ajax_showOptions(this,'donhangsua',event)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tautocomplete=\"on\"style=\"width:100%\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"left\"width=\"15%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\"name=\"tensp1\"id=\"tensp1\"value=\"\"style=\"width:100%\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"center\"width=\"6%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"number\"name=\"soluong\"value=\"\"style=\"width:100%;text-align:center;color:black;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"right\"width=\"6%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\"name=\"donvitinh1\"value=\"\"style=\"width:100%;text-align:center;color:black;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"right\"width=\"8%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\"name=\"dongia1\"id=\"dongia1\"value=\"\"style=\"width:100%;text-align:center;color:black;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"center\" width=\"6%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\"name=\"chietkhau1\" value=\"\"style=\"width:100%;text-align:center;color:black;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td align=\"right\"width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\"name=\"thanhtien1\"value=\"\"style=\"width:100%;text-align:center;color:black;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\treadonly=\"readonly\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");

														}
													
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr class=\"tbfooter\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td colspan=\"12\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tbody>\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\t");
 sp.DBClose(); 
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\treplaces();\r\n");
      out.write("\tdropdowncontent.init(\"noidungGhiChu\", \"right-botom\", 500, \"click\");\r\n");
      out.write("\tjQuery(function(){\r\n");
      out.write("\t\t$(\"#smartId\").autocomplete(\"khachhanglistAjax.jsp\");\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
